version: "3.9"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  extrator:
    build: .
    volumes:
      - ./dados_brutos:/app/dados_brutos
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - minio
    command: >
      sh -c "
        python extracao/api/api.py &&
        python extracao/csv/csv.py &&
        python extracao/database/database.py &&
        python uploader/uploader.py
      "

  db_warehouse:
    image: postgres:13
    environment:
      POSTGRES_DB: ibm_dw
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data 

  data_loader:
    build: .
    volumes:
      - ./dados_processados:/app/dados_processados
    environment:
      PGHOST: db_warehouse
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: ibm_dw
    depends_on:
      - db_warehouse
    command: tail -f /dev/null 

  transformador:
    build: .
    volumes:
      - ./dados_processados:/app/dados_processados
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      PGHOST: db_warehouse
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: ibm_dw
    depends_on:
      - minio
      - db_warehouse
    command: python processamento/transformar_dados.py

volumes:
  minio_data:
  pg_data:
